<?php
					$loihayall = array(
						'Đừng đi qua thời gian mà không để lại dấu vết, Bao giờ ta cũng phải luôn luôn có một nơi nào để đến,[br] Trí tuệ của con người trưởng thành trong tĩnh lặng, còn tính cách trưởng thành trong bão táp',
						'Mong rằng bạn luôn có đủ hạnh phúc để vui vẻ, đủ thử thách để mạnh mẽ hơn, [br]đủ nỗi buồn để bạn trưởng thành hơn và đủ tiền để mua quà cho bạn bè.',
						'Khi bạn ở ngoài sáng, tất cả mọi thứ đều theo bạn,[br] nhưng khi bạn bước vào bóng tối,[br] ngay cả cái bóng của bạn cũng không đi theo bạn nữa',
						'Cứ tiến lên. Cứ tiến lên.[br] Tôi đã mắc mọi sai lầm có thể phạm phải. Nhưng tôi vẫn tiến lên.',
						'Tôi rất biết ơn tất cả những người đã nói KHÔNG với tôi.[br] Nhờ vậy mà tôi biết cách tự mình giải quyết sự việc.',
						'1. Hãy cười lên và cả thế giới sẽ cười cùng bạn, nếu khóc, bạn sẽ phải chỉ khóc một mình.',
						'2. Nếu bạn không thể xây dựng một thành phố thì hãy xây lấy một trái tim hồng.',
						'3. Một người bạn thật sự là người bước vào cuộc sống của bạn khi cả thế giới đã bước ra.',
						'4. Yêu thương cho đi là yêu thương có thể giữ được mãi mãi.',
						'5. Một nụ cười có thể thay đổi một ngày, một cái ôm có thể thay đổi một tuần, một lời nói có thể thay đổi một cuộc sống.',
						'6. Nếu bạn không thể là Mặt Trời thì cũng đừng làm một đám mây.',
						'7. Hãy là một con tem, gắn chặt vào mục tiêu cho tới khi đến đích.',
						'8. Có hai nơi mà không gì là không thể xảy ra : trong giấc mơ và trong tình yêu.',
						'9. Nếu bạn luôn cố để giống một người nào đó, bạn sẽ đánh mất những gì đặc biệt nhất về chính mình.',
						'10. Cuộc sống giống như hoa hồng, vẻ đẹp luôn đi cùng với gai.',
						'11. Chẳng sao cả nếu bạn cố, và cố, và cố nữa, nhưng vẫn thất bại.[br] Nhưng thật tệ hại nếu bạn cố rồi thất bại, và không muốn cố lần nữa.',
						'12. Chỉ khi bạn mở được cánh cửa của lòng tin, bạn mới mở tới cánh cửa của tình bạn.',
						'13. Một tâm hồn không có trí tưởng tượng cũng như một nhà quan sát không có kính thiên văn.',
						'14. Khi bạn có thể cười ngay cả trong thất bại, đó là bạn đã đạt tới thành công thật sự.',
						'15. Mỗi ngày đều là ngày đầu tiên của phần còn lại trong cuộc sống của bạn.',
						'16. Không bao giờ có thang máy đi tới thành công, bạn luôn phải đi cầu thang bộ.',
						'17. Một người thông minh giống như một dòng sông, càng sâu thì càng ít gây ồn ào.',
						'18. Tình yêu là khi chúng ta nhận ra chính mình ở trong một người khác, và tự hào vì điều đó!',
						'19. Bạn trưởng thành không phải khi biết tự chăm lo cho mình, mà là khi bạn có thể chăm lo cho người khác.',
						'20. Tình bạn là một sợi chỉ bằng vàng nối trái tim của cả thế giới.',
						'21. Bạn cần phải đứng vững vì ít nhất một điều gì đó, nếu không, bạn sẽ ngã vì bất kỳ điều gì.',
						'22. Hãy luôn nhớ rằng mỗi người bạn tốt đều đã từng là một người xa lạ.',
						'23. Dù bạn không giỏi nhất, nhưng hãy cố gắng cao nhất.',
						'24. Trái Đất là một con tàu lớn mà không hề có hành khách, tất cả chúng ta đều là thuỷ thủ.',
						'25. Hãy cười như thể không ai đang nhìn bạn, và sống như thể không gì có thể ngăn cản bạn.',
						'26. Chẳng có dấu hiệu nào ghi trên cái kén rằng nó sẽ trở thành một con bướm xinh đẹp.',
						'27. Để vẽ một bức tranh hoàn hảo, nhất thiết bạn sẽ cần một vài màu tối.',
						'28. Lo lắng quá nhiều giống như việc trả nợ mà bạn không biết có vay hay không.',
						'29. Muốn nhìn thấy cầu vồng, bạn phải biết chịu đựng cơn mưa.',
						'30. Nếu bạn muốn thành công, đừng sợ thất bại.',
						'31. Hạnh phúc không tuỳ thuộc vào bạn là ai, bạn làm gì mà tùy thuộc vào bạn nghĩ gì.',
						'32. Cách tốt nhất để có một ý tưởng xuất sắc là có thật nhiều ý tưởng.',
						'33. Trái tim tôi mỉm cười khi bạn bước lại gần và nói "xin chào!"',
						'34. Đôi khi những điều nhỏ bé nhất lại mang đến những điều kỳ diệu nhất.',
						'35. Dũng cảm là vượt qua nỗi sợ hãi chứ không phải không sợ hãi.',
						'36. Cái đầu quá nóng và trái tim quá lạnh không bao giờ giải quyết được việc gì.',
						'37. Thắp nến lên đi, đừng ngồi than vãn trong bóng tối.',
						'38. Tâm trí bạn giống như chiếc ô : chỉ hoạt động khi nó được mở.',
						'39. Hãy để mọi người nhớ mãi nụ cười của bạn.',
						'40. Mỗi cuốn sách là một bức tranh kì diệu về cuộc sống.',
						'41. Bí quyết để có một đôi môi đẹp : hãy nói những lời tử tế.',
						'42. Học tập chỉ mở cửa, bạn phải tự bước qua cánh cửa đó.',
						'43. Thành công lớn nhất là đứng dậy sau mỗi lần bị vấp ngã.',
						'44. Bạn không bao giờ bị đánh bại, cho đến khi bạn tự bỏ cuộc.',
						'45. "Và tôi nhận ra rằng, trong cuộc sống luôn luôn có (ít nhất) một người dõi theo một người bằng cả trái tim,[br] để rồi (có thể) người đó lại dõi theo người khác với tất cả tấm lòng của họ.[br] Nhưng có hề gì, chỉ cần bạn được yêu thương ai đó và "yêu thương vô điều kiện",[br] cuộc sống sẽ vô cùng ý nghĩa. Và với tôi, thế là đủ!" (Trích từ một truyện ngắn trên báo HHT)',
						'46. Ai yêu mãnh liệt thì ít lời.',
						'47. Đời thay đổi khi chúng ta thay đổi. (Tựa đề một quyển sách rất nổi tiếng của Andrew Matthew ^_^)',
						'48. "Chúng ta sinh ra là để lấp đầy cho nhau. Như những mảnh xếp hình với dáng vẻ kỳ dị,[br] đầy những ưu điểm và khiếm khuyết, sở trường và sở đoản, là vô nghĩa dù hiện hữu,[br] nếu không lấp đầy cho nhau, để tạo nên một thế gian rực rỡ và hoàn hảo." (Trích từ "Trò chuyện đầu tuần" trên báo HHT.)',
						'49. "Tôi đã luôn tin chắc rằng ai cũng có thể tìm thấy những điều đẹp nhất ở những nơi ít ngờ tới nhất, chỉ cần thật sự để tâm. Và tôi đã đúng." (HHT)',
						'50. "Bây giờ thì con hiểu, yêu và thương luôn là và phải là một… [br]Yêu thương là khí trời, là nắng ấm giúp cây non lớn lên, em là búp măng non, em lớn lên trong mùa yêu thương… [br]Em biết, an lành và hạnh phúc chỉ có khi em yêu thương." (HHT)',
						'51. "Hãy năng động, sáng tạo, mơ những gì muốn mơ, làm những gì mình muốn làm, đến những nơi mình muốn đến.[br] Hãy là một phần ý nghĩa của cuộc đời chính bạn và những người xung quanh bạn." (HHT)',
						'52. Hãy khám phá những điều nhỏ nhoi đang làm cho cuộc sống tốt đẹp hơn. Những khoảnh khắc ấy là những hạt vàng trên lối đi toàn sỏi đá… Để ta nhận ra rằng "Cuộc đời là một điều kỳ diệu". (Trái tim có điều kỳ diệu)',
						'53. Tất cả kho tàng trên trái đất không thể nào so sánh nổi với hạnh phúc gia đình. (Calderon)',
						'54. Một người vĩ đại là một người đã không đánh mất trái tim trẻ thơ của mình. (Mencius)',
						'55. Nơi nào có tình thương yêu, thì nơi đó luôn có những điều kỳ diệu. (Loilla Cather)',
						'56. Yêu thương là cái gì đó vĩnh cửu. (Vincenl Van Gohg)',
						'57. Con cái được giáo dục sẵn nếu chính cha mẹ được giáo dục. (Goethe)',
						'58. Một số người tặng thời gian, một số người tặng tiền, một số tặng kỹ năng tay nghề và mối quan hệ,[br] một số đã hiến máu… Và ai cũng có một thứ gì đó để trao tặng. (Barbara Bush)',
						'59. Lòng yêu thương là điều mà chúng ta có thể mang theo khi chúng ta ra đi,[br] và nó khiến cho giây phút cuối trở nên dễ dàng chịu đựng. (Louisa May Alcott)',
						'60. Tình yêu không có thời hạn, chừng nào trái tim còn đập người ta còn yêu. (Karamzin)',
						'61. Hãy có lòng nhân ái, bởi vì bất kỳ ai bạn gặp đều đang chiến đấu gian khổ hơn bạn. (Plato)',
						'62. Phải yêu bạn vì hạnh phúc thương yêu không vì lợi lộc có thể khai thác được. (La Bruyere)',
						'63. Nguyên nhân chính của các lỗi lầm loài người mắc phải được tìm thấy trong những thành kiến được thu thập từ thời thơ ấu. (Descartes)',
						'64. Tình bạn là nhận thêm niềm vui và chia bớt nỗi buồn. (Thomas Fuller)',
						'65. Đứng sau động từ "yêu thương" thì "giúp đỡ" là động từ đẹp nhất trên thế giới. (Bertha Von Suttner) ',
						'66. Có những tình cảm sống suốt cả đời và chỉ chấm dứt cùng với đời sống. (Fosefine)',
						'67. Đừng bao giờ mất kiên nhẫn, đó chính là chiếc chìa khoá cuối cùng mở được cửa. (Saint Exupery)',
						'68. Trong tâm hồn cao thượng tất cả đều cao thượng. (Pascal)',
						'69. Tình thương yêu là một trái cây luôn nở rộ và vừa tầm hái. (Mẹ Terasa)',
						'70. Người lạc quan cho đấy là cái bánh, kẻ bi quan lại thấy đó là cái lỗ tròn.',
						'71. Nhân từ, ngọt ngào là dấu hiệu của tính cao thượng. (Pythagore)',
						'72. Bởi vì ông Trời không thể có mặt ở khắp mọi nơi nên ông mới tạo ra các bà mẹ. (Ngạn ngữ Do Thái)',
						'73. Trong xã giao đừng đổi bạn thành thù mà hãy đổi thù thành bạn. (Pythagore)',
						'74. Cái gì mà chúng ta học được ở tuổi thơ thì luôn còn mãi. (Cerventes)',
						'75. Thực trạng không phải là thứ bạn ao ước có,[br] cũng không phải là thứ mọi người thấy mà là thứ thực sự là như thế. (Robert J. Ringer)',
						'76. Trẻ em : không chỉ là những người bé. [br]Trẻ em thật sự là những con người đặc biệt. [br]Trên đời này không ai giống trẻ em cả.',
						'Khi bạn sinh ra đời, bạn khóc còn mọi người xung quanh cười. [br]Hãy sống sao cho khi bạn qua đời, mọi người khóc còn bạn, bạn cười.',
						'Bao lâu bạn vẫn còn tự tin ở bạn, thì người khác vẫn còn tin bạn - Cynda Williams',
						'Bạn có yêu đời không? Vậy đừng phung phí thời gian vì chất liệu của cuộc sống được làm bằng thời gian. - Franklin',
						'Dù người ta có nói với bạn điều gì đi nữa,[br] hãy tin rằng cuộc sống là điều kỳ diệu và đẹp đẽ - Pautopxki',
						'Bắc thang lên hỏi ông trời: sao không xuống đất lại ngồi trên cao? [br]Ông trời quát: hỏi tào lao! bây vừa động đất, làm sao tao ngồi? ',
						'Sự học là vô hạn,đời người là hữu hạn.[br] Không nên lấy cái hữu hạn phục vụ cho cái vô hạn !',
						'Sống có lúc hèn lúc sang [br]Khi nhai giò chả, khi sàng cơm thiu',
						'Người đàn ông chinh phục thế giới bằng sức mạnh và trí tuệ,[br] người phụ nữ chinh phục thế giới bằng cách chinh phục đàn ông ',
						'Điều sai lầm nhất là phải phủ nhận những gì trái tim mình thật sự cảm nhận!!! ',
						'Con đường thong dong đi đến lòng người là nói về những điều họ thích. - Dale Carnegie',
						'- Đừng bao giờ sợ cố gắng làm cho mọi thứ tốt hơn,[br] bạn sẽ ngạc nhiên với kết quả mà bạn đạt được.',
						'Tôi đã học được từ cuộc sống: [br] khi một người không yêu mến tôi như tôi như tôi mong muốn, không có nghĩa là họ không yêu mến tôi hết lòng...',
						'Không có người phụ nữ xấu, chỉ có người phụ nữ ... không đẹp.',
						'- Đừng bao giờ sợ việc cho đi khi bạn vẫn còn thứ để cho.',
						'Chỉ có kẻ sáng suốt mới biết là mình ngu [br]Và chỉ có kẻ Ngu mới cho mình là sáng suốt',
						'Cái giường mà biết nói năng thì ông hàng xóm hàm răng không còn',
						'Hôm nay phải hơn hôm qua nhưng không bằng ngày mai! ',
						'Hãy cảm ơn những gì bạn muốn mà không được, [br]vì nếu được thì bạn sẽ không còn gì để mong đợi.',
						'Hãy cảm ơn khi bạn không biết một điều gì đó,[br] vì nó sẽ tạo cho bạn cơ hội để học hỏi.',
						'Hãy cảm ơn những giờ phút khó khăn, [br]vì đó là thời gian để bạn trưởng thành.',
						'Hãy cảm ơn những nhược điểm của bạn, [br]vì nó cho bạn cơ hội để cải thiện.',
						'Hãy cảm ơn những sai lầm của bạn, [br]vì nó sẽ dạy bạn những bài học có giá trị.',
						'Hãy cảm ơn khi bạn mệt mỏi và kiệt sức,[br] vì đó có nghĩa rằng bạn đang cố gắng thay đổi.',
						'Một cuộc sống tràn đầy phong phú đến với những người cũng biết cảm ơn cho những gì thất bại.',
						'Hãy tìm cách cảm ơn những ngày gian khổ của bạn để chúng trở thành những ân điển.',
						'Không có vấn đề gì là không có cách giải quyết nếu ko có cách giải quyết thì...[br]chẳng có vấn đề gì cà.',
						'Quyết không yêu lấy tiền uống rượu[br]Sống cô độc cho gái chết già ',
						'Hãy học cách nói câu cảm ơn nó sẽ giúp bạn trưởng thành hơn! ',
						'Nói hoài nói mãi . Nói hơi nhiều mà chằng nói được nhiều câu có nghĩa',
						'Ai đã từng đi lui, đi tới, đi lui, đi tới, đi lui, .... đi hoài không tới?',
						'Thật ra có rất ít phụ nữ đẹp. Không phải vì phụ nữ không biết làm đẹp mà vì họ làm hoài mà ...vẩn không đẹp ',
						'Ngày mai em đi... lạy chúa xin em đừng về! [br] Mod nào onl cho xin 500 nhạc bài biển nhớ ',
						'Nghệ thuật che lấp sự bất tài cũng đòi hỏi không ít tài năng.',
						'Phụ nữ đem lại niềm vui nhưng không phải lúc nào cũng vậy , còn thuốc lá thì lúc nào cũng có khói.',
						'Con đường ngắn nhất để đi từ một trái tim đến 1 trái tim là con đường truyền máu.',
						'Lương tâm là cái gì đó cảm thấy tổn thương trong khi các phần khác của cơ thể cảm thấy dễ chịu.',
						'Bạn có thể mua một người trung thực không ? [br]Không ! nhưng bán một người như vậy dễ hơn .',
						'Share to be shared',
						'Sắc sắc không không [br] sắc tức thị không, không tức thị sắc',
						'Vạn sự tùy duyên [br] Nếu đã biết trăm năm là hữu hạn, cớ gì ta không sống thật sâu…?',
						'Tôi đã học được từ cuộc sống:[br] mình phải mất nhiều năm để tạo lòng tin nơi người khác nhưng lại có thể đánh mất nó chỉ trong một giây ...',
						'Tôi đã học được từ cuộc sống:[br] tôi phải luôn cẩn trọng vì những lỗi lầm tôi gây ra trong một khoảnh khắc, có thể làm tôi hối hận cả một đời .... ',
						'Tôi đã học được từ cuộc sống:[br] mình phải mất nhiều năm để tạo lòng tin nơi người khác nhưng lại có thể đánh mất nó chỉ trong một giây ... ',
						'Tôi đã học được từ cuộc sống:[br] tôi không thể bắt người khác yêu mến mình, tất cả những điều tôi có thể lảm là cố gắng trở thành một người đáng được yêu mến ...',
						'24 điều nên nhớ : [br]1. Sự hiện diện của bạn là món quà của cả thế giới.',
						'24 điều nên nhớ : [br]10. Có nhiều giấc mơ đang chờ được thực hiện.',
						'24 điều nên nhớ : [br]11. Những quyết định cũng không kém phần quan trọng như những cơ hội mà bạn có.',
						'24 điều nên nhớ : [br]12. Hãy vươn đến đỉnh cao của chính bạn, vươn tới ước mơ và khát vọng.',
						'24 điều nên nhớ : [br]13. Không gì làm lãng phí năng lượng của bạn hơn là ngồi một chỗ và lo lắng về hàng tá chuyện.',
						'24 điều nên nhớ : [br]14. Một người kiên nhẫn có thể chấp nhận một việc thậm chí còn hơn cả bản chất của sự việc đó.',
						'24 điều nên nhớ : [br]15. Đừng biến bất cứ điều gì trở nên trầm trọng.',
						'24 điều nên nhớ : [br]16. Hãy sống một cuộc sống thanh bình, đừng sống một cuộc đời tiếc nuối.',
						'24 điều nên nhớ : [br]17. Hãy nhớ rằng một tình yêu nhỏ có thể đi cả một quãng đường dài.',
						'24 điều nên nhớ : [br]18. Cũng hãy nhớ rằng nhiều thứ sẽ ra đi mãi mãi và không bao giờ quay trở lại.',
						'24 điều nên nhớ : [br]19. Hãy nhớ rằng tình bạn là một sự đầu tư khôn ngoan.',
						'24 điều nên nhớ : [br]2. Bạn là duy nhất và không ai giống bạn cả.',
						'24 điều nên nhớ : [br]20. Cuộc sống thật quý giá khi người ta ở bên nhau.',
						'24 điều nên nhớ : [br]21. Hãy nhận ra rằng mọi thứ không bao giờ là trễ cả.',
						'24 điều nên nhớ : [br]22. Hãy thực hiện những điều bình dị theo những cách phi thường nhất.',
						'24 điều nên nhớ : [br]23. Hãy luôn nhớ về gia đình, luôn có những ước mơ, hy vọng và niềm hạnh phúc trong cuộc sống.',
						'24 điều nên nhớ : [br]24. Thời gian luôn chuyển động và hãy ước rằng, một lúc nào đó, ta sẽ vươn tới những vì sao.',
						'24 điều nên nhớ : [br]3. Cuộc sống của bạn hoàn toàn phụ thuộc theo mong muốn của bạn.',
						'24 điều nên nhớ : [br]4. Hãy biết tận hưởng trọn vẹn một ngày.',
						'24 điều nên nhớ : [br]5. Hãy đếm những điều mà bạn hạnh phúc, đừng đếm những điều phiền muộn.',
						'24 điều nên nhớ : [br]6. Bạn sẽ vượt qua được tất cả mọi thứ, dù có khó khăn đến đâu.',
						'24 điều nên nhớ : [br]7. Có hàng tá câu hỏi và câu trả lời trong chính bạn.',
						'24 điều nên nhớ : [br]8. Hãy trở nên có hiểu biết, can đảm và mạnh mẽ.',
						'24 điều nên nhớ : [br]9. Đừng tự tạo những giới hạn cho chính bản thân bạn.',
						'Tình yêu là vĩnh cửu. Trong tình yêu, thứ duy nhất có thể thay đổi đó chính là người yêu.',
						'Đừng bi quan, trong cái rủi nó còn có cái xui…',
						'Thứ gì mua được bằng tiền thì thứ đó ... RẺ !',
						'Theo lý thuyết thì lý thuyết không khác với thực tế là mấy, nhưng theo thực tế thì thực tế khác xa lý thuyết.',
						'Đời là bể khổ mà chúng sanh thì... không biết bơi!',
						'Bạn có biết ai mà bạn ghét nhất và căm thù nhấtkhông. Đó chính là... kẻ thù của bạn',
						'Xấu không chịu được. Mãi về sau mới chịu được',
						'Đừng bao giờ xem tivi màquên chưa cắm điện, và nhớ là đang ăn thì không được đánh răng đâu đấy',
						'Tất cả đều có thể, trừ những thứ không thể!!!',
						'Vịt là 1 loài có 2 chân, chạy nhanh hơn... rùa, bay cao hơn... chuột, tuy nhiên lại bơi kém con... cá',
						'Cách tốt nhất để giữ lời hứa là đừng hứa gì cả.',
						'Tôi sẽ giúp bạn bỏ một thói quen xấu... Đó là thở!',
						'Không cần mình đẹp .Chỉ cần người khác xấu.',
						'Tui có thể cưỡng lại tất cả mọi thứ ....... trừ sự cám dỗ',
						'Tự hào từ bàn tay trắng, ta tạo nên ... vô số nợ.',
						'"Không lúc nào phụ nữ mạnh bằng lúc họ lấy tình yêu ra làm vũ khí tự vệ" (Depphot)',
						'Rõ ràng là trên đời này không có gì là rõ ràng'

					);





					$loihay = $loihayall[rand(0, count($loihayall) - 1)];

					
?>